# Book settings
title: Deep Thought
author: Daniel Correia
logo: logo.png

repository:
  url: https://github.com/DanReia/deepthought
  path_to_book: ./book/
html:
  use_repository_button: true
  home_page_in_navbar: true
  use_issues_button: true
